name: Build and Push Docker Image

on:
  release:
    types: [ created, published ]
  workflow_dispatch:
  workflow_run:
    workflows: ["Auto Create Release"]
    types:
      - completed
    branches:
      - main

# Cấp quyền cho GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get latest release
        if: github.event_name == 'workflow_run'
        id: get_latest_release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            if (releases.length === 0) {
              core.setFailed('No releases found');
              return;
            }
            const latestRelease = releases[0];
            const tagName = latestRelease.tag_name;
            core.setOutput('tag_name', tagName);
            return tagName;
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        continue-on-error: true
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.event_name == 'release' && github.event.release.tag_name || steps.get_latest_release.outputs.tag_name || 'latest' }}
            latest
        continue-on-error: true
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags || 'ghcr.io/${{ github.repository }}:latest' }}
          labels: ${{ steps.meta.outputs.labels }}
        continue-on-error: true 