name: Build and Push Docker Image

on:
  release:
    types: [ created, published ]
  workflow_dispatch:
  workflow_run:
    workflows: ["Auto Create Release"]
    types:
      - completed
    branches:
      - main
      - develop

# Cấp quyền cho GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get latest release
        if: github.event_name == 'workflow_run'
        id: get_latest_release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            if (releases.length === 0) {
              core.setFailed('No releases found');
              return;
            }
            const latestRelease = releases[0];
            core.setOutput('is_prerelease', latestRelease.prerelease.toString());
            return latestRelease.tag_name;
      
      - name: Set build type
        id: set_build_type
        run: |
          if [[ "${{ github.event_name }}" == "workflow_run" && "${{ steps.get_latest_release.outputs.is_prerelease }}" == "true" ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
            echo "DOCKER_TAG_SUFFIX=-dev" >> $GITHUB_ENV
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
            echo "DOCKER_TAG_SUFFIX=" >> $GITHUB_ENV
          fi
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        continue-on-error: true
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
        continue-on-error: true
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags || format('ghcr.io/{0}:latest{1}', github.repository, env.DOCKER_TAG_SUFFIX) }}
          labels: ${{ steps.meta.outputs.labels }}
        continue-on-error: true 