name: Build Windows MSIX Package

on:
  release:
    types: [ created, published ]
  workflow_dispatch:
  workflow_run:
    workflows: ["Auto Create Release"]
    types:
      - completed
    branches:
      - main

# Cấp quyền cho GITHUB_TOKEN
permissions:
  contents: write  # Cần thiết để tải lên tệp vào releases

jobs:
  build-msix:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get latest release
        if: github.event_name == 'workflow_run'
        id: get_latest_release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            if (releases.length === 0) {
              core.setFailed('No releases found');
              return;
            }
            const latestRelease = releases[0];
            core.setOutput('upload_url', latestRelease.upload_url);
            return latestRelease.upload_url;
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build MSIX Package
        run: flutter pub run msix:create
        continue-on-error: true
      
      - name: Check MSIX file and create placeholder if needed
        run: |
          $msixPath = "build/windows/x64/runner/Release/keyviz.msix"
          if (-Not (Test-Path $msixPath)) {
            Write-Host "MSIX file not found, creating placeholder"
            New-Item -ItemType Directory -Force -Path build/windows/x64/runner/Release
            New-Item -ItemType File -Force -Path $msixPath
            Set-Content -Path $msixPath -Value "MSIX build failed"
          }
      
      - name: Upload MSIX Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url || steps.get_latest_release.outputs.upload_url }}
          asset_path: ./build/windows/x64/runner/Release/keyviz.msix
          asset_name: keyviz-windows.msix
          asset_content_type: application/octet-stream 